# Submit QPS arrivals for HOLD_PERIOD seconds.
QPS=1
HOLD_PERIOD=300
RAMP_UP_TIME=0
RAMP_UP_STEPS=1
MAX_CONCURRANCY=900
QUERY_TIMEOUT=300
LIMIT_RESULTSET=1000
MAX_ERROR_PCT=5
RECYCLE_ON_EOF=true
RANDOM_ORDER=false
GENERATE_DASHBOARD=true
