# Maintain a fixed number of in-flight queries for HOLD_PERIOD seconds.
CONCURRENT_QUERY_COUNT=2
HOLD_PERIOD=300
RAMP_UP_TIME=0
RAMP_UP_STEPS=1
QUERY_TIMEOUT=300
LIMIT_RESULTSET=1000
MAX_ERROR_PCT=5
RECYCLE_ON_EOF=true
RANDOM_ORDER=false
GENERATE_DASHBOARD=true
