version: '3.3'
services:
  db:
    image: mysql:5.7
    restart: always
    env_file:
      - env
    ports:
      - '3306:3306'
    volumes:
      - my-db:/var/lib/mysql
  backend:
    image: us-docker.pkg.dev/e6data-analytics/e6-platform-public/api-demo:1.0.11
    env_file:
      - env
    ports:
      - "3001:8000"
    depends_on:
      - db
  frontend:
    image: us-docker.pkg.dev/e6data-analytics/e6-platform-public/ui-demo:1.0.8
    env_file:
      - env
    ports:
      - "3000:3000"
    depends_on:
      - backend
volumes:
  my-db:
